language: nodejs
nodejs:
  - "12.19.1"

services:
  - docker

before_install:
  - docker build -t shrikant9867/nodejs-prod -f Dockerfile.dev .

script:
  - docker run -e CI=true shrikant9867/nodejs-prod npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-nodejs"
  env: "Docker-nodejs-env"
  bucket_name: "elasticbeanstalk-ap-south-1-426842546120"
  bucket_path: "docker-nodejs"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
